
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.Action;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.border.Border;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author perer
 */
public class NewJFrame extends javax.swing.JFrame {

    private Object frame;
    private Component emptyLabel;
    protected Action leftAction, middleAction, rightAction;
    private Object converttotextfield;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        topimagepanel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        ratesbutton = new javax.swing.JButton();
        historybutton = new javax.swing.JButton();
        trackingbutton = new javax.swing.JButton();
        offlinebutton = new javax.swing.JButton();
        switchtoappbutton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        loginregisterbutton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        convertfromfield = new javax.swing.JTextField();
        converttofield = new javax.swing.JTextField();
        convertfromdropbox = new javax.swing.JComboBox<>();
        converttodropbox = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        enteramountlfield = new javax.swing.JLabel();
        enterthevaluetextfield = new javax.swing.JTextField();
        convertnowbutton = new javax.swing.JButton();
        errortextmessagelabel = new javax.swing.JLabel();
        sideimagepanel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(50, 50));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jPanel7.setBackground(new java.awt.Color(51, 51, 255));
        jPanel7.setForeground(new java.awt.Color(51, 153, 255));

        jLabel1.setBackground(new java.awt.Color(102, 255, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("CCon");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        topimagepanel.setBackground(new java.awt.Color(0, 102, 102));
        topimagepanel.setIcon(new javax.swing.ImageIcon("C:\\Users\\perer\\OneDrive\\Pictures\\Saved Pictures\\cc3.jfif")); // NOI18N
        topimagepanel.setText("imagepanel");
        topimagepanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                topimagepanelMouseEntered(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\perer\\OneDrive\\Pictures\\Saved Pictures\\cc5.jfif")); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(topimagepanel, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(topimagepanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 0));
        jPanel4.setLayout(new java.awt.GridLayout(0, 1));

        jPanel8.setBackground(new java.awt.Color(0, 102, 0));

        ratesbutton.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        ratesbutton.setLabel("Rates");
        ratesbutton.setName("ratesbutton"); // NOI18N
        ratesbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ratesbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratesbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ratesbuttonMouseExited(evt);
            }
        });
        ratesbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratesbuttonActionPerformed(evt);
            }
        });

        historybutton.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        historybutton.setText("History");
        historybutton.setName("historybutton"); // NOI18N
        historybutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                historybuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                historybuttonMouseExited(evt);
            }
        });
        historybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historybuttonActionPerformed(evt);
            }
        });

        trackingbutton.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        trackingbutton.setText("Tracking");
        trackingbutton.setName("trackingbutton"); // NOI18N
        trackingbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                trackingbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                trackingbuttonMouseExited(evt);
            }
        });
        trackingbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackingbuttonActionPerformed(evt);
            }
        });

        offlinebutton.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        offlinebutton.setText("Offline");
        offlinebutton.setName("offlinebutton"); // NOI18N
        offlinebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                offlinebuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                offlinebuttonMouseExited(evt);
            }
        });
        offlinebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offlinebuttonActionPerformed(evt);
            }
        });

        switchtoappbutton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        switchtoappbutton.setText("Switch to App");
        switchtoappbutton.setName("switchtoappbutton"); // NOI18N
        switchtoappbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                switchtoappbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                switchtoappbuttonMouseExited(evt);
            }
        });
        switchtoappbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchtoappbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ratesbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(historybutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(trackingbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
            .addComponent(offlinebutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(switchtoappbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(ratesbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(historybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(trackingbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(offlinebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(switchtoappbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel4.add(jPanel8);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        loginregisterbutton.setText("Login/Register");
        loginregisterbutton.setToolTipText("");
        loginregisterbutton.setName("loginregisterbutton"); // NOI18N
        loginregisterbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginregisterbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginregisterbuttonMouseExited(evt);
            }
        });
        loginregisterbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginregisterbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(loginregisterbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(loginregisterbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 102));

        jPanel5.setBackground(new java.awt.Color(0, 153, 160));

        jTextArea1.setBackground(new java.awt.Color(0, 153, 160));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("The Fastest way to convert currency...");
        jScrollPane1.setViewportView(jTextArea1);

        convertfromfield.setBackground(new java.awt.Color(0, 153, 190));
        convertfromfield.setText("Convert from");
        convertfromfield.setName("convertfromlabel"); // NOI18N
        convertfromfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                convertfromfieldMouseEntered(evt);
            }
        });
        convertfromfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertfromfieldActionPerformed(evt);
            }
        });

        converttofield.setBackground(new java.awt.Color(0, 153, 190));
        converttofield.setText("Convert to");
        converttofield.setName("converttolabel"); // NOI18N

        convertfromdropbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "EUR", "JPY", "GBP", "CHF", "CAD" }));
        convertfromdropbox.setToolTipText("abc");
        convertfromdropbox.setName("convertfromdropbox"); // NOI18N
        convertfromdropbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertfromdropboxActionPerformed(evt);
            }
        });

        converttodropbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "EUR", "JPY", "GBP", "CHF", "CAD", "AUD" }));
        converttodropbox.setToolTipText("acd");
        converttodropbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                converttodropboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(convertfromfield, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(convertfromdropbox, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(converttofield, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(converttodropbox, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(converttofield)
                        .addComponent(converttodropbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(convertfromfield, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(convertfromdropbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(0, 153, 160));

        enteramountlfield.setBackground(new java.awt.Color(0, 153, 190));
        enteramountlfield.setText("Enter the amount");
        enteramountlfield.setName("enteramountlabel"); // NOI18N
        enteramountlfield.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                enteramountlfieldInputMethodTextChanged(evt);
            }
        });
        enteramountlfield.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                enteramountlfieldPropertyChange(evt);
            }
        });

        enterthevaluetextfield.setText("Enter the value");
        enterthevaluetextfield.setName("enterthevaluetextfield"); // NOI18N
        enterthevaluetextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterthevaluetextfieldActionPerformed(evt);
            }
        });
        enterthevaluetextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enterthevaluetextfieldKeyPressed(evt);
            }
        });

        convertnowbutton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        convertnowbutton.setText("Convert now");
        convertnowbutton.setName("convertnowbutton"); // NOI18N
        convertnowbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                convertnowbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                convertnowbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                convertnowbuttonMouseExited(evt);
            }
        });
        convertnowbutton.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                convertnowbuttonInputMethodTextChanged(evt);
            }
        });
        convertnowbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertnowbuttonActionPerformed(evt);
            }
        });

        errortextmessagelabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        errortextmessagelabel.setForeground(new java.awt.Color(0, 51, 51));
        errortextmessagelabel.setName("errormessagelabel"); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(enteramountlfield, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterthevaluetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(errortextmessagelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addComponent(convertnowbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enteramountlfield, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enterthevaluetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(errortextmessagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(convertnowbutton)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        sideimagepanel.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(sideimagepanel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(sideimagepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void convertfromfieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convertfromfieldMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_convertfromfieldMouseEntered

    private void convertfromfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertfromfieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_convertfromfieldActionPerformed

    private void topimagepanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topimagepanelMouseEntered
        // TODO add your handling code here:
        
//        BackgroundPanel panel = new BackgroundPanel( yourImage );
//    frame.setContentPane( panel );
//    frame.add(northPanel, BorderLayout.PAGE_START);
//    frame.add(centerPanel, BorderLayout.CENTER);
        
    }//GEN-LAST:event_topimagepanelMouseEntered

    private void enteramountlfieldInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_enteramountlfieldInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_enteramountlfieldInputMethodTextChanged

    private void enteramountlfieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_enteramountlfieldPropertyChange
        // TODO add your handling code here:
        //success.setText("successfukky entered amount");
        
    }//GEN-LAST:event_enteramountlfieldPropertyChange

    public String getText() {
        return convertfromdropbox+""+toString();
    }

    private void convertfromdropboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertfromdropboxActionPerformed
        // TODO add your handling code here:
          //String convertfrom=(String) JComboBox.getSelectedItem();
        String[] convertfromdropbox = { "Bird", "Cat", "Dog", "Rabbit", "Pig" };
        // get the selected item:
    
    }//GEN-LAST:event_convertfromdropboxActionPerformed

    private void enterthevaluetextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterthevaluetextfieldActionPerformed
        // TODO add your handling code here:
        // MA - Using the class field myString to receive text from text area
        String enterthevaluetextfield = JOptionPane.showInputDialog(null, "First number to add");
		while (!StringUtils.isNumericSpace(enterthevaluetextfield)) {
			enterthevaluetextfield = JOptionPane.showInputDialog(null,
					"Invalid first number. Please insert another number");
		}
                
        
        
        
    }//GEN-LAST:event_enterthevaluetextfieldActionPerformed

    private void ratesbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratesbuttonActionPerformed
        // TODO add your handling code here:
        
        dispose();
        Rates u1=new Rates();
        u1.setVisible(true);
        
        
        
    }//GEN-LAST:event_ratesbuttonActionPerformed

    private void historybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historybuttonActionPerformed
        // TODO add your handling code here:
        dispose();
        History u1=new History();
        u1.setVisible(true);
    }//GEN-LAST:event_historybuttonActionPerformed

    private void trackingbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackingbuttonActionPerformed
        // TODO add your handling code here:
        dispose();
        Tracking u1=new Tracking();
        u1.setVisible(true);
    }//GEN-LAST:event_trackingbuttonActionPerformed

    private void offlinebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offlinebuttonActionPerformed
        // TODO add your handling code here:
        dispose();
        Offline u1=new Offline();
        u1.setVisible(true);
    }//GEN-LAST:event_offlinebuttonActionPerformed

    private void ratesbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratesbuttonMouseEntered
        // TODO add your handling code here:
       
        
                        ratesbutton.setBackground(new Color(0, 255, 0));

    }//GEN-LAST:event_ratesbuttonMouseEntered

    private void ratesbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratesbuttonMouseExited
        // TODO add your handling code here:
                        ratesbutton.setBackground(new Color(240, 240, 240));

    }//GEN-LAST:event_ratesbuttonMouseExited

    private void historybuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historybuttonMouseEntered
        // TODO add your handling code here:
                        historybutton.setBackground(new Color(0, 255, 0));

    }//GEN-LAST:event_historybuttonMouseEntered

    private void historybuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historybuttonMouseExited
        // TODO add your handling code here:
                        historybutton.setBackground(new Color(240, 240, 240));

    }//GEN-LAST:event_historybuttonMouseExited

    private void trackingbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trackingbuttonMouseEntered
        // TODO add your handling code here:
                        trackingbutton.setBackground(new Color(0, 255, 0));

    }//GEN-LAST:event_trackingbuttonMouseEntered

    private void trackingbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trackingbuttonMouseExited
        // TODO add your handling code here:
                        trackingbutton.setBackground(new Color(240, 240, 240));

    }//GEN-LAST:event_trackingbuttonMouseExited

    private void offlinebuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_offlinebuttonMouseEntered
        // TODO add your handling code here:
                        offlinebutton.setBackground(new Color(0, 255, 0));

    }//GEN-LAST:event_offlinebuttonMouseEntered

    private void offlinebuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_offlinebuttonMouseExited
        // TODO add your handling code here:
                        offlinebutton.setBackground(new Color(240, 240, 240));

    }//GEN-LAST:event_offlinebuttonMouseExited

    private void ratesbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratesbuttonMouseClicked
        // TODO add your handling code here:
        //Compound borders
        Border compound;
        Border redline = BorderFactory.createLineBorder(Color.red);
    }//GEN-LAST:event_ratesbuttonMouseClicked

    private void convertnowbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convertnowbuttonMouseEntered
        // TODO add your handling code here:
        convertnowbutton.setBackground(new Color(240, 90, 240));
    }//GEN-LAST:event_convertnowbuttonMouseEntered

    private void convertnowbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convertnowbuttonMouseExited
        // TODO add your handling code here:
        convertnowbutton.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_convertnowbuttonMouseExited

    private void convertnowbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convertnowbuttonMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_convertnowbuttonMouseClicked

    private void convertnowbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertnowbuttonActionPerformed
        // TODO add your handling code here:
        //default title and icon
        ArrayList<String> s=new ArrayList<>();
        s.add((String) convertfromdropbox.getSelectedItem());
        s.add((String) converttodropbox.getSelectedItem());
        s.add((String) enterthevaluetextfield.getText());

        new Confirmation(s).setVisible(true);
        
                //ArrayList<String> t=new ArrayList<>();
                //t.add((String) converttodropbox.getSelectedItem());
        //new Confirmation(t).setVisible(true);
        
        //ArrayList<String> u=new ArrayList<>();
          //      u.add((String) enterthevaluetextfield.getText());
        //new Confirmation(u).setVisible(true);



        

    }//GEN-LAST:event_convertnowbuttonActionPerformed

    private void converttodropboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_converttodropboxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_converttodropboxActionPerformed

    private void convertnowbuttonInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_convertnowbuttonInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_convertnowbuttonInputMethodTextChanged

    private void enterthevaluetextfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enterthevaluetextfieldKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            enterthevaluetextfield.setEditable(false);
            //set error message
            //errortextmessagelabel.setText("Enter numbers only");
            
            JOptionPane.showMessageDialog(enterthevaluetextfield, "Please enter numeric values only", "Error", JOptionPane.ERROR_MESSAGE);
            
        }
        else{
            enterthevaluetextfield.setEditable(true);
        }
    }//GEN-LAST:event_enterthevaluetextfieldKeyPressed

    private void loginregisterbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginregisterbuttonActionPerformed
        // TODO add your handling code here:
        dispose();
        LoginRegister u1=new LoginRegister();
        u1.setVisible(true);
    }//GEN-LAST:event_loginregisterbuttonActionPerformed

    private void switchtoappbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchtoappbuttonActionPerformed
        // TODO add your handling code here:
        dispose();
        SwitchToApp u1=new SwitchToApp();
        u1.setVisible(true);
    }//GEN-LAST:event_switchtoappbuttonActionPerformed

    private void loginregisterbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginregisterbuttonMouseEntered
        // TODO add your handling code here:
        loginregisterbutton.setBackground(new Color(240, 50, 240));
        
    }//GEN-LAST:event_loginregisterbuttonMouseEntered

    private void loginregisterbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginregisterbuttonMouseExited
        // TODO add your handling code here:
        loginregisterbutton.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_loginregisterbuttonMouseExited

    private void switchtoappbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switchtoappbuttonMouseEntered
        // TODO add your handling code here:
        switchtoappbutton.setBackground(new Color(240, 50, 240));
    }//GEN-LAST:event_switchtoappbuttonMouseEntered

    private void switchtoappbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switchtoappbuttonMouseExited
        // TODO add your handling code here:
        switchtoappbutton.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_switchtoappbuttonMouseExited

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> convertfromdropbox;
    private javax.swing.JTextField convertfromfield;
    private javax.swing.JButton convertnowbutton;
    private javax.swing.JComboBox<String> converttodropbox;
    private javax.swing.JTextField converttofield;
    private javax.swing.JLabel enteramountlfield;
    private javax.swing.JTextField enterthevaluetextfield;
    private javax.swing.JLabel errortextmessagelabel;
    private javax.swing.JButton historybutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton loginregisterbutton;
    private javax.swing.JButton offlinebutton;
    private javax.swing.JButton ratesbutton;
    private javax.swing.JLabel sideimagepanel;
    private javax.swing.JButton switchtoappbutton;
    private javax.swing.JLabel topimagepanel;
    private javax.swing.JButton trackingbutton;
    // End of variables declaration//GEN-END:variables

    private static class BackgroundPanel {

        public BackgroundPanel() {
        }
    }

    private static class Second_Jframe {

        public Second_Jframe() {
        }

        private void setSize(int i, int i0) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        private void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }

    private static class rates {

        public rates() {
        }

        private void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }

    private static class e {

        private static Object getSource() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public e() {
        }
    }
}
